[project]
name = "restaurant-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.2",
    "openai>=1.82.1",
    "starlette>=0.47.0",
    "uvicorn>=0.34.3",
]
